name: Mark stale issues and pull requests

on:
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
        days-before-stale: 30
        days-before-close: 9999999
        stale-pr-message: 'This pr is stale because it has been open 30 days with no activity. We are looking at it how we can include your code changes.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-label: '6.0'
        exempt-pr-label: '6.0'
